// hello-vue/src/components/ShopHeader.vue
<template>
  <header>
    <img src="https://dummyimage.com/200x100/000/fff&text=Logo" alt="" />
    <nav>
        <ul>
            <!-- <li><a href="">Videos to rent</a></li>
            <li><a href="">Videos to buy</a></li>
            <li><a href="">Used DVDs</a></li>
            <li><a href="">Offers</a></li> -->

            <li v-for="menu in $store.state.menuItems" :key="menu"><a href="">{{menu}}</a></li> <!--  v:for == directive 라고 함, 
                                                                                      key 는 다른 값이 나와야함. 내부적으로 구분하기 위해-->
        </ul>
    </nav>
  </header>
</template>

<script>
export default {

  props: [
    // 'menus'
  ]
}
</script>

<style>

</style>

// hello-angular/src/app/shop-header/shop-header.component.ts
import { Component, Input, OnInit } from '@angular/core';   // Input import 해줘야함.

@Component({
  selector: 'app-shop-header',
  templateUrl: './shop-header.component.html',
  styleUrls: ['./shop-header.component.css']
})
export class ShopHeaderComponent implements OnInit {    // LifeCycle method

  @Input() menus: string[] = [];    // 초기화 해줌.(데이터를 받지 않았을경우 처리) 데이터는 @Input 사용
  // @Input('menus') myMenus: string[] = [];  // 부모에게서 받은 변수명을 사용하지 않고 다른 변수명을 사용할 경우
                                              // @Input 에 파라미터로 부모에게 받은 변수명을 넣어주고 선언할 때 다른 변수명으로 선언
                                              
  //@Input() menus?: string[];        // null 허용. 변수명 뒤에 '?' 있을 시 nullable

  constructor() { }

  ngOnInit(): void {
  }

}

<header>
    <img src="https://dummyimage.com/200x100/000/fff&text=Logo" alt="" />
    <nav>
        <ul>
            <!-- <li><a href="">{{ menus[0] }}</a></li>
            <li><a href="">Videos to buy</a></li>
            <li><a href="">Used DVDs</a></li>
            <li><a href="">Offers</a></li> -->

            <li *ngFor="let menu of menus"><a href="">{{ menu }}</a></li>   <!-- angular for 문 문법 (*ngFor="javascript for 문")-->
        </ul>
    </nav>
</header>
